on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  run-tests:
    runs-on: ubuntu-18.04
    name: A job for laravel test
    steps:
      - name: Github checkout
        uses: actions/checkout@v1
      - name: Laravel tests
        uses: lucasemanuel/laravel-test-action@v2
