on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  run-tests:
    runs-on: ubuntu-18.04
    name: A job for laravel test
    steps:
      - run: $GITHUB_ACTION_PATH/script.sh
        shell: bash
      - name: Github checkout
        uses: actions/checkout@v1
      - name: Laravel tests
        uses: hdev14/laravel-test-action@v1
